### ISSUE TITLE
Use python3 instead of python in README.md

### ISSUE THREAD

**Issue by aryoda** [kanroot/men_of_war_assault_squad_2_linux#1]
If I follow your instructions in the README.md I get this error on Ubuntu 20.04:

```
~/temp/men_of_war_assault_squad_2_linux (master)  > gedit main.py
~/temp/men_of_war_assault_squad_2_linux (master)  > python main.py
  File "main.py", line 26
    def DeletePAK(path_zip: str):
                          ^
SyntaxError: invalid syntax
```

I propose to change the python call to:

`python3 main.py`

in the README.md to avoid this problem (and it did work then in my case).

Thanks for your great script BTW :-)

**Comment by kanroot** [comment]
Thanks for advice. Any future problem with script tell me.
